###################nothing#####################
DELETE FROM SURVEY_SETTING WHERE SURVEY_ID NOT IN (SELECT ID FROM SURVEY);
DELETE FROM SURVEY_ACCESS_TOKEN WHERE SURVEY_ID NOT IN (SELECT ID FROM SURVEY);
DELETE FROM SURVEY_RESPONSE WHERE SURVEY_ID NOT IN (SELECT ID FROM SURVEY);
DELETE FROM QUESTION WHERE SURVEY_ID NOT IN (SELECT ID FROM SURVEY);
DELETE FROM QUATA WHERE SURVEY_ID NOT IN (SELECT ID FROM SURVEY);
