DELETE FROM QUESTION;
DELETE FROM SURVEY_SETTING;
DELETE FROM SURVEY;

INSERT SURVEY (ID,USER_ID,SERVICE_ID,TITLE,DESCRIPTION,WELCOME_TEXT,END_TEXT,END_URL,END_URL_DESCRIPTION,TERMINATION_TEXT,ACTIVE,QUESTION_COUNT,START_TIME,EXPIRY_TIME,CREATE_TIME,UPDATE_TIME) VALUES(1,'zhangsan','crm','性格情景调查','测试的目的是反应最真实的足迹，而不是别人所期待的你。本测试时一种性格测试，从星座、血型、价值观等反应和描述测试者的性格特质。 请最大程度放松下来，选择当您面临下述这些情况时的不由自主、自然和不假思索的决定或倾向。','欢迎你','问卷填写结束','http://www.baidu.com','百度一下，你就知道','问卷被终止',TRUE,20,'2017-05-26 11:04:07','2018-05-26 11:04:07',NOW(),NOW());
INSERT SURVEY_SETTING(SURVEY_ID,RESPONSE_LIMIT,TEMPLATE,ACCESS_RULE,`FORMAT`,`LOCALE`,ENABLE_ASSESSMENT,ENABLE_CAPTCHA,ALLOW_EDIT_AFTER_COMPLETION,ALLOW_PREV,ALLOW_SUSPEND,AUTO_REDIRECT,SHOW_RESPONSE,SHOW_GROUP_INFO,SHOW_PROGRESS,SHOW_QUESTION_INDEX,SHOW_WELCOME) VALUES(1,1000,'bootstrap','PUBLIC','ALL_IN_ONE','zh_CN',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE);
INSERT QUESTION (ID,SURVEY_ID,PARENT_ID,QUESTION_TYPE,QUESTION_CODE,`INDEX`,TITLE,IMAGE,`HELP`,CONTENT,MANDATORY,DEFAULT_ANSWER,CREATE_TIME,UPDATE_TIME)VALUES(1,1,NULL,'LONG_FREE_TEXT','article',1,'请写一片文章',NULL,'以XX为题，写一篇800字左右的文章',NULL,TRUE,NULL,NOW(),NOW());
INSERT QUESTION (ID,SURVEY_ID,PARENT_ID,QUESTION_TYPE,QUESTION_CODE,`INDEX`,TITLE,IMAGE,`HELP`,CONTENT,MANDATORY,DEFAULT_ANSWER,CREATE_TIME,UPDATE_TIME)VALUES(2,1,NULL,'LONG_FREE_TEXT','article2',1,'请写一片文章',NULL,'以XX为题，写一篇1000字左右的文章',NULL,TRUE,NULL,NOW(),NOW());

